### ISSUE TITLE
Found another one.

### ISSUE THREAD

**Issue by BandBoxBrawl** [HexCodeFFF/mediaforge#101]
### Describe the bug

![Screenshot_2022-05-20-12-21-27-39](https://user-images.githubusercontent.com/32648777/169517585-b0edc840-3ea1-4271-9d18-55b0038a421c.jpg)

### Traceback

[traceback-1.txt](https://github.com/HexCodeFFF/mediaforge/files/8739106/traceback-1.txt)
I forgot to delete the other one so it's -1.

**Comment by HexCodeFFF** [comment]
Weird that this isn't handled by the hosting error code

Common error caused by not enough resources on the server
