### ISSUE TITLE
I don't know

### ISSUE THREAD

**Issue by BandBoxBrawl** [HexCodeFFF/mediaforge#105]
### Describe the bug

See screenshot.

### Traceback

[traceback (2).txt](https://github.com/HexCodeFFF/mediaforge/files/8886578/traceback.2.txt)

### Anything Else

![Screenshot_2022-06-12-20-09-56-50](https://user-images.githubusercontent.com/32648777/173249500-598fe341-914c-4a9e-b674-5283731e9d90.jpg)

**Comment by HexCodeFFF** [comment]
Ugh this bug again
I'll add a more user-friendly error but it'll be fixed in the rewrite
