### ISSUE TITLE
cant start on docker DESKTOP

### ISSUE THREAD

**Issue by zarigata** [HexCodeFFF/mediaforge#107]
### Describe the bug

RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from cog_botevents import BotEventsCog
  File "/mediaforge/cog_botevents.py", line 5, in <module>
    from mainutils import prefix_function
  File "/mediaforge/mainutils.py", line 23, in <module>
    import improcessing
  File "/mediaforge/improcessing.py", line 32, in <module>
    import autotune
  File "/mediaforge/autotune.py", line 4, in <module>
    import AutoTune

### Traceback

no traceback

### Expected Behavior

run docker

### Steps To Reproduce

1: open CMD 
2:imput the clone and run commands
3:error apears

**Comment by realmercy** [comment]
I have the same issue on a cloud hosting service

**Comment by zarigata** [comment]
> I have the same issue on a cloud hosting service

how did you fixed?

**Comment by realmercy** [comment]
I couldn't, I even tried doing 
`pip install numpy --upgrade` thinking that would resolve it but it didn't

**Comment by zarigata** [comment]
> I couldn't, I even tried doing `pip install numpy --upgrade` thinking that would resolve it but it didn't

as well as me, even tried to make an save on it on the image, no luck, thanks anyway

**Comment by HexCodeFFF** [comment]
> I couldn't, I even tried doing `pip install numpy --upgrade` thinking that would resolve it but it didn't

this is because you need to enter the poetry venv with `poetry shell` before running pip commands or it wont affect mediaforge. i updated the poetry locks so pulling the latest code and updating pip packages should fix it.
