### ISSUE TITLE
Command ('ffmpeg', '-i', 'temp/jPvhvntj.mp4', '-af', 'volume=33.219280948873624dB', '-strict', '-1', '-c:a', 'libmp3lame', 'temp/wEWktdAx.mp4') failed.

### ISSUE THREAD

**Issue by Bruhman69420XD** [HexCodeFFF/mediaforge#111]
wont go up

**Comment by HexCodeFFF** [comment]
Please send the attached traceback.txt file.

**Comment by Bruhman69420XD** [comment]
[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/9174789/traceback.txt)

**Comment by HexCodeFFF** [comment]
Hmm I think I recognize this error, ffmpeg glitches out when the volume is set too high sometimes. No fix that im aware of.

**Comment by Bruhman69420XD** [comment]
ok
