### ISSUE TITLE
Command ('ffmpeg', '-hide_banner', '-i', 'temp/ulkLqfZZ.mp4', '-vsync', '1', 'temp/ulkLqfZZ_%09d.png') failed.

### ISSUE THREAD

**Issue by dfault-user** [HexCodeFFF/mediaforge#117]
hjelp

im on selfhost btw
[traceback-1.txt](https://github.com/HexCodeFFF/mediaforge/files/9366688/traceback-1.txt)

**Comment by HexCodeFFF** [comment]
Does this always happen when you run the scene command on the same media or does it only happen sometimes?
If it always happens, can you set the log level to debug and send the entire bot log here please after running the command

**Comment by dfault-user** [comment]
reproducible by literally using the docker container on latest updates done
by the script, and the container is also broken when rebuilding

fixed by installing manually
Thanks,
Brandan Delafuente
***@***.***
