### ISSUE TITLE
Bot wont do as intended

### ISSUE THREAD

**Issue by Intragste** [HexCodeFFF/mediaforge#120]
### Describe the issue

Bot wont accept files but other commands do work
[traceback.1.txt](https://github.com/HexCodeFFF/mediaforge/files/9536367/traceback.1.txt)

### Expected Behavior

That the bot will accept the files

### Logs

![image](https://user-images.githubusercontent.com/113193256/189376910-0d7e9533-ddda-4d40-ab9a-62db8098d30e.png)

### Config

  GNU nano 5.4                                            config.py *                                                   # COPY THIS FILE INTO A FILE CALLED config.py AND CHANGE THE VALUES AS NEEDED.
# discord API bot token https://discord.com/developers/applications
bot_token = no
# tenor API key https://tenor.com/developer/keyregistration
tenor_key = "KEYHERE"
# BotBlock tokens. see https://pypi.org/project/discordlists.py/
bot_list_data = None
# bot_list_data = {
#         "examplebotlist.com": {
#             "token": "exampletoken"
#         },
# }

# the number of instances of chromedriver to run for caption processing.
# more means faster processing of videos and better under heavy load but also uses more PC resources!
chrome_driver_instances = 20
# NOTICE is recommended, INFO prints more information about what bot is doing, WARNING only prints errors.
log_level = "NOTICE"
# maximum number of frames for an input file.
max_frames = 1024
# amount of seconds cooldown per user commands have. set to 0 to disable cooldown
cooldown = 3
# minimum height/width that media will be sized up to if below
min_size = 100
# maximum height/width that media will be downsized to if above
max_size = 2000

### Hosting Provider

My own machine

### Hosting Method

Docker is not in AutoMode

### Hosting Resources

5gb of ram

**Comment by HexCodeFFF** [comment]
Can you change the log level to "DEBUG" and send the output of the command?

**Comment by Intragste** [comment]
No I didnt, should I do that now?

**Comment by Intragste** [comment]
Yeah i'll try

**Comment by Intragste** [comment]
I attempted this, it just sent out this file.
[traceback (1).txt](https://github.com/HexCodeFFF/mediaforge/files/9537123/traceback.1.txt)
