### ISSUE TITLE
caption command won’t work 

### ISSUE THREAD

**Issue by AlqhemyA** [HexCodeFFF/mediaforge#138]
heres the traceback
 DATETIME:2022-12-07 02:02:36.395320
COMMAND:$caption school fire drills
TRACEBACK:
processing.common.CMDError: ffmpeg version 5.1.2 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-9)
  configuration: --disable-decoder=amrnb --disable-decoder=libopenjpeg --disable-gnutls --disable-liblensfun --disable-libopencv --disable-podpages --disable-sndio --disable-stripping --enable-avfilter --enable-chromaprint --enable-frei0r --enable-gcrypt --enable-gpl --enable-ladspa --enable-libaom --enable-libaribb24 --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libdavs2 --enable-libdc1394 --enable-libdrm --enable-libfdk-aac --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libkvazaar --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librsvg --enable-librubberband --enable-libshine --enable-libsmbclient --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-nonfree --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-openssl --enable-postproc --enable-pthreads --enable-shared --enable-version3 --enable-vulkan --incdir=/usr/include/x86_64-linux-gnu --libdir=/usr/lib/x86_64-linux-gnu --prefix=/usr --toolchain=hardened --enable-vaapi --enable-libmfx --enable-libvmaf --enable-libilbc --disable-altivec --shlibdir=/usr/lib/x86_64-linux-gnu
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, png_pipe, from '/dev/shm/mediaforge/HDfyVIdS.png':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: png, rgba(pc), 480x86 [SAR 2835:2835 DAR 240:43], 25 fps, 25 tbr, 25 tbn
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from '/dev/shm/mediaforge/fUbPrYFw.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2022-12-07T02:02:20.000000Z
  Duration: 00:00:11.13, start: 0.000000, bitrate: 3143 kb/s
  Stream #1:0[0x1](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
    Metadata:
      creation_time   : 2022-12-07T02:02:20.000000Z
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
  Stream #1:1[0x2](und): Video: h264 (Main) (avc1 / 0x31637661), yuvj420p(pc, bt709, progressive), 480x640, 3010 kb/s, 31.72 fps, 60 tbr, 600 tbn (default)
    Metadata:
      creation_time   : 2022-12-07T02:02:20.000000Z
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
      encoder         : H.264
    Side data:
      displaymatrix: rotation of 90.00 degrees
Stream mapping:
  Stream #0:0 (png) -> format:default (graph 0)
  Stream #1:1 (h264) -> format:default (graph 0)
  vstack:default (graph 0) -> Stream #0:0 (png)
  Stream #1:0 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[swscaler @ 0x55df6dfc3c40] [swscaler @ 0x55df6dfd1900] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x55df6dfc3c40] [swscaler @ 0x55df6dff2c00] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x55df6dfc3c40] [swscaler @ 0x55df6e0130c0] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x55df6dfc3c40] [swscaler @ 0x55df6e033f80] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x55df6dfc3c40] [swscaler @ 0x55df6e054440] deprecated pixel format used, make sure you did set range correctly
[Parsed_vstack_2 @ 0x55df6de685c0] Input 1 width 640 does not match input 0 width 480.
[Parsed_vstack_2 @ 0x55df6de685c0] Failed to configure output pad on Parsed_vstack_2
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #1:1
[aac @ 0x55df6d74cc80] Qavg: 185.157
[aac @ 0x55df6d74cc80] 2 frames left in the queue on closing
Conversion failed!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/mediaforge-HXFskkj--py3.11/lib/python3.11/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/commands/caption.py", line 115, in captioncommand
    await process(ctx, processing.vips.vipsutils.generic_caption_stack, [["VIDEO", "GIF", "IMAGE"]],
  File "/mediaforge/src/core/process.py", line 157, in process
    raise e
  File "/mediaforge/src/core/process.py", line 125, in process
    result = await run()
             ^^^^^^^^^^^
  File "/mediaforge/src/core/process.py", line 108, in run
    command_result = await func(*args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/processing/vips/vipsutils.py", line 23, in generic_caption_stack
    return await processing.ffmpeg.naive_vstack(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mediaforge/src/processing/ffmpeg.py", line 556, in naive_vstack
    await run_command("ffmpeg", "-i", file0, "-i", file1, "-filter_complex",
  File "/mediaforge/src/processing/common.py", line 75, in run_command
    raise CMDError(f"Command {args} failed.") from CMDError(result)
processing.common.CMDError: Command ('ffmpeg', '-i', '/dev/shm/mediaforge/HDfyVIdS.png', '-i', '/dev/shm/mediaforge/fUbPrYFw.mov', '-filter_complex', '[0]format=pix_fmts=yuva420p[0f];[1]format=pix_fmts=yuva420p[1f];[0f][1f]vstack=inputs=2', '-c:v', 'png', '-fs', '1G', '-fps_mode', 'vfr', '/dev/shm/mediaforge/gaQuCUVw.mp4') failed.

**Comment by HexCodeFFF** [comment]
This isn't #147 it's the same bug as #129 oops
