### ISSUE TITLE
[Errno 28] No space left on device MediaForge discord bot

### ISSUE THREAD

**Issue by ClovekNeznamy** [HexCodeFFF/mediaforge#139]
Hi, i need help. Commands $ytdownload and $dl do not work and keep sending this error message. I have no idea what does it mean. 
<:eemark:803791399710883871> `OSError: Command raised an exception: OSError: [Errno 28] No space left on device`

**Comment by ClovekNeznamy** [comment]
[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/10195029/traceback.txt)

**Comment by HexCodeFFF** [comment]
the fun thing about this is what used to be a minor problem about files being left in the temp directory now becomes a full-on memory leak because temp files are stored in memory thanks to the magic of /dev/shm

**Comment by TrentTrentTrent** [comment]
the leak of memory 😱😱😱😱😱😱😱😱😱😱😱😱😱

**Comment by HexCodeFFF** [comment]
Seems to be stable for now. Closing.
