### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by h3artcrushz** [HexCodeFFF/mediaforge#140]
### Describe the bug

didn't caption the gif 

### Traceback

[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/10202957/traceback.txt)

**Comment by HexCodeFFF** [comment]
for once there's not enough information inthe traceback to debug this. can you send the media that reliably reproduces this issue?

**Comment by machineonamission** [comment]
> Error media?

Dude if you keep spamming my GitHub I will ban you from it
