### ISSUE TITLE
Missing Access

### ISSUE THREAD

**Issue by yourizuring** [HexCodeFFF/mediaforge#154]
### Describe the bug

Trying to upload an image in my discord server and then doing /esmcaption or /caption while it's BELOW the image causes Mediaforge to return with '<:eemark:803791399710883871> `discord.app_commands.errors.CommandInvokeError: Hybrid command raised an error: Command 'caption' raised an exception: Forbidden: 403 Forbidden (error code: 50001): Missing Access`'

### Traceback

[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/10536702/traceback.txt)

### Expected Behavior

The image to generate with the caption. 

### Steps To Reproduce

1. Send an image or GIF
2. Run command /esmcaption or /caption
3. See error.

**Comment by HexCodeFFF** [comment]
The bot requires the channel history permission in order to gather the required media.
