### ISSUE TITLE
Command 'videodl' raised an exception: NonBugError: Resulting file is 109.3 MB. Aborting upload since resulting file is over 100.0 MB

### ISSUE THREAD

**Issue by lawnmower500** [HexCodeFFF/mediaforge#156]
my friend tried to convert a yt vid to a file and this happened
[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/10583080/traceback.txt)

**Comment by HexCodeFFF** [comment]
Did you read the error? “Resulting file is 109.3 MB. Aborting upload since resulting file is over 100.0 MB”
Discord only supports uploading 8MB
