### ISSUE TITLE
Command ('ffmpeg', '-i', '/dev/shm/mediaforge/InHGZoph.png', '-i', '/dev/shm/mediaforge/pPCJQpLO.gif', '-filter_complex', '[0]format=pix_fmts=yuva420p[0f];[1]format=pix_fmts=yuva420p[1f];[0f][1f]vstack=inputs=2', '-c:v', 'png', '-fs', '1G', '-fps_mode', 'vfr', '/dev/shm/mediaforge/MCfLgWyL.mp4') failed.

### ISSUE THREAD

**Issue by SirDarwin** [HexCodeFFF/mediaforge#158]
[traceback](https://cdn.discordapp.com/attachments/803806089237889025/1072991075901394955/traceback.txt)
Happened after using /uncaption on a Tenor gif.
[The gif in question](https://tenor.com/view/kekw-gif-21672467)
[Discord upload the command was used on](https://cdn.discordapp.com/attachments/803806089237889025/1072990554037682376/kekw.gif)
I've had this issue a few times over the past few days but only thought to look at the github now.
Backreading it seems this is often a problem with ffmpeg/Tenor, but I thought I should submit it anyways, since if it is a bigger issue then a larger sample size never hurts right?

**Comment by HexCodeFFF** [comment]
See #147
