### ISSUE TITLE
Command ('ffmpeg', '-y', '-i', '/dev/shm/mediaforge/cyoXHLGGvtOH.mp4', '-c:v', 'h264', '-b:v', '663.9909337925311', '-pass', '1', '-f', 'mp4', '-passlogfile', '/dev/shm/mediaforge/bcSxziFU', '/dev/null') failed.

### ISSUE THREAD

**Issue by R4TF4N69** [HexCodeFFF/mediaforge#161]
[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/10777719/traceback.txt)

**Comment by HexCodeFFF** [comment]
duplicate of #70

**Comment by HexCodeFFF** [comment]
this issue occurs when your video is so big that when mediaforge attempts to fit it into discord ffmpeg freaks out so try not to do that
