### ISSUE TITLE
$trollface command doesn’t work on static images

### ISSUE THREAD

**Issue by CPsWasTaken** [HexCodeFFF/mediaforge#169]
troll command doesn't work 
[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/11336263/traceback.txt)

**Comment by HexCodeFFF** [comment]
Finally a bug I can actually reproduce and debug
A fix should be out soon:tm:, I’ll close this issue when it is
For those curious, I think I messed up the troll ffmpeg command so it only works with videos/gifs and it gets confused for static images
