### ISSUE TITLE
Ffmpeg: Error muxing a packet

### ISSUE THREAD

**Issue by TheVisual** [HexCodeFFF/mediaforge#178]
[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/11641917/traceback.txt)

https://github.com/HexCodeFFF/mediaforge/assets/132447890/2c3728b3-ad6b-4d35-88d1-88d837529ca4

**Comment by HexCodeFFF** [comment]
It’s times like these where I am eternally grateful that GitHub lets the repo owner edit other people’s issues

**Comment by HexCodeFFF** [comment]
Actually wait fuck was that video the one that caused the error? I thought it was just a random meme

**Comment by TheVisual** [comment]
@HexCodeFFF yes it was the video

**Comment by HexCodeFFF** [comment]
My bad, video is back on the issue. Genuinely thought it was just a random meme

I’ll see if I can reproduce the issue tomorrow. Yet again it’s an error in ffmpeg, not in my code, so I’m not sure a fix on my end is possible, but I’ll see what I can do.

**Comment by TheVisual** [comment]
if it helps @HexCodeFFF to reproduce i set the pitch to 3 then tried to caption it

**Comment by HexCodeFFF** [comment]
yes that should help. Thank you for providing reproduction steps.
