### ISSUE TITLE
Twitter videos won't download

### ISSUE THREAD

**Issue by boobies112** [HexCodeFFF/mediaforge#185]
hi yes i was trying to get this video from Twitter i thought was funny (video https://twitter.com/landon_mcrae/status/1674861461104132096?t=twkwdGTvQ7mPBRl1bmGg-w&s=19)
and it unexpectedly stopped and wouldn't work after trying multiple times

**Comment by HexCodeFFF** [comment]
Known issue

Twitter made it so you need to login to see anything on the site so downloads are broken for now

When I get back from vacation in 2 weeks I’ll add some login details

See https://github.com/yt-dlp/yt-dlp/issues/7473

**Comment by HexCodeFFF** [comment]
closed with https://github.com/HexCodeFFF/mediaforge/commit/92b10be165c59bd47c6dd239cb70a0d0f37963a8
