### ISSUE TITLE
Input 1 width 399 does not match input 0 width 400

### ISSUE THREAD

**Issue by g-l-i-t-c-h-o-r-s-e** [HexCodeFFF/mediaforge#188]
```$addaudio 1``` with an image and 8 minute long mp3 attached to the message

**Comment by HexCodeFFF** [comment]
Please send the full traceback.txt

**Comment by g-l-i-t-c-h-o-r-s-e** [comment]
> Please send the full traceback.txt

[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/12114735/traceback.txt)

**Comment by HexCodeFFF** [comment]
Duplicate of #129
