### ISSUE TITLE
Magick doesn't support videos only on mobile no more

### ISSUE THREAD

**Issue by Jamieisbest** [HexCodeFFF/mediaforge#205]
### Describe the bug

How do you redo this stuff

### Traceback

No traceback

### Expected Behavior

<:wmark:803791399782580284> Media #1 is VIDEO, it must be: IMAGE

### Steps To Reproduce

1. Send the media
2. Redo the video thing
3. Idk what else

### Anything Else

idk

**Comment by HexCodeFFF** [comment]
This is intentional behavior. When I rewrote the bot I intentionally and somewhat lazily decided not to add support for videos because it’s an extremely intensive command. I’ll make this a suggestion and do a poll in the discord about if people want it back

**Comment by Jamieisbest** [comment]
Thanks!

**Comment by HexCodeFFF** [comment]
![image](https://github.com/HexCodeFFF/mediaforge/assets/35177464/ec272387-d4a5-4a5b-b454-095cd044b33b)
People don't want it back so gonna close this
