### ISSUE TITLE
Ffmpeg: corrupted double-linked list

### ISSUE THREAD

**Issue by Tarluk99** [HexCodeFFF/mediaforge#215]
### Describe the bug

discord.app_commands.errors.CommandInvokeError: Hybrid command raised an error: Command 'caption' raised an exception: CMDError: Command ('ffmpeg', '-i', '/dev/shm/mediaforge/NxVSEvUV.png', '-i', '/dev/shm/mediaforge/UyhARlff.gif', '-filter_complex', '[0]format=pix_fmts=yuva420p[0f];[1]format=pix_fmts=yuva420p[1f];[0f][1f]vstack=inputs=2', '-c:v', 'png', '-fs', '1G', '-fps_mode', 'vfr', '/dev/shm/mediaforge/VuZTJSny.mp4') failed.

### Traceback

[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/13173063/traceback.txt)

### Expected Behavior

I clicked the /caption command on the MediaForge bot's About Me page to add a top caption to a gif.

### Steps To Reproduce

3. See traceback file

**Comment by HexCodeFFF** [comment]
See #147
