### ISSUE TITLE
Command ('ffmpeg', '-i', 'temp/gYtSDnFo.mp4', '-ar', '48000', '-af', 'asetrate=r=15481909,atempo=0.5263426013194779,atempo=0.5263426013194779,atempo=0.5263426013194779,atempo=0.5263426013194779,atempo=0.5263426013194779,atempo=0.5263426013194779,atempo=0.5263426013194779,atempo=0.5263426013194779,atempo=0.5263426013194779,aresample=48000', '-strict', '-1', '-c:a', 'aac', 'temp/NAKhNltx.mp4') failed.

### ISSUE THREAD

**Issue by piotrek117studos** [HexCodeFFF/mediaforge#45]
DATETIME:2021-11-14 15:11:30.485844
COMMAND:$pitch 100
TRACEBACK:
improcessing.CMDError: ffmpeg version 4.3.2-0york0~18.04 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version='0york0~18.04' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libzimg --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'temp/gYtSDnFo.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
  Duration: 00:00:18.95, start: 0.000000, bitrate: 3321 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709/bt709/smpte170m), 1920x1080 [SAR 1:1 DAR 16:9], 3193 kb/s, 30 fps, 30 tbr, 90k tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[Parsed_atempo_1 @ 0x562c5b4bd580] Failed to configure input pad on Parsed_atempo_1
Error reinitializing filters!
Failed to inject frame into filter network: Cannot allocate memory
Error while processing the decoded data for stream #0:1
Conversion failed!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hex/.local/share/virtualenvs/captionbot-iutiqbOm/lib/python3.8/site-packages/nextcord/ext/commands/core.py", line 168, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 1073, in pitch
    await improcess(ctx, improcessing.pitch, [["VIDEO", "AUDIO"]], numofhalfsteps)
  File "main.py", line 481, in improcess
    raise e
  File "main.py", line 460, in improcess
    result = await func(filesforcommand, *args)
  File "/home/hex/Desktop/captionbot/improcessing.py", line 1185, in pitch
    await run_command("ffmpeg", "-i", file, "-ar", "48000", "-af", af, "-strict", "-1", "-c:a",
  File "/home/hex/Desktop/captionbot/improcessing.py", line 149, in run_command
    raise CMDError(f"Command {args} failed.") from CMDError(stdout.decode().strip() + stderr.decode().strip())
improcessing.CMDError: Command ('ffmpeg', '-i', 'temp/gYtSDnFo.mp4', '-ar', '48000', '-af', 'asetrate=r=15481909,atempo=0.5263426013194779,atempo=0.5263426013194779,atempo=0.5263426013194779,atempo=0.5263426013194779,atempo=0.5263426013194779,atempo=0.5263426013194779,atempo=0.5263426013194779,atempo=0.5263426013194779,atempo=0.5263426013194779,aresample=48000', '-strict', '-1', '-c:a', 'aac', 'temp/NAKhNltx.mp4') failed.

**Comment by HexCodeFFF** [comment]
Please post tracebacks in code blocks

This seems to be an issue of just system memory and is probably related to the absurd number of atempos in this Lol
