### ISSUE TITLE
Using $twittercaption on this .gif spits out a long error log. (log included in post)

### ISSUE THREAD

**Issue by Blatantist** [HexCodeFFF/mediaforge#56]
![image](https://user-images.githubusercontent.com/71236124/152468411-0899ee0b-4724-41a8-b84c-1a5c5584ed75.png)
The gif I tried: https://tenor.com/view/cake-spy-kids-spy-kids-three-gif-22259371
I can't tell if $twittercaption is an image-only effect, or if it errored out for another reason.
Error log:
[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/7999886/traceback.txt)

**Comment by HexCodeFFF** [comment]
it says in the error log that one frame is one pixel too big. i have no idea why that would happen though... ill give it a look. i'd bet if you try again it would probably work though if you get the same "frame 13 has the wrong size" error every time that's a Big issue

**Comment by Blatantist** [comment]
alright, thanks for the quick response!

**Comment by Blatantist** [comment]
I tried the same exact gif+caption and it worked this time. Strange that it errored like that.
