### ISSUE TITLE
Add $uncaption command.

### ISSUE THREAD

**Issue by Blatantist** [HexCodeFFF/mediaforge#57]
A command I often used to use on esmBot (before I switched to mediaforge) was &uncaption (Recropping the image, gif, etc.). I would love if you could make it work on both $caption and $esmcaption (I personally don't like the default font on $caption).

Also, unrelevant question: I see that there's feature requests both in Issues and Discussions. Where do you prefer people to post feature requests?

**Comment by HexCodeFFF** [comment]
Issues are easier to deal with generally so probably issues

I’ll have a look at esmbot’s code and see how it implements it

**Comment by Blatantist** [comment]
Alright thank you!

**Comment by Blatantist** [comment]
I'm continually amazed at how quickly you respond to issues and requests! Thank you for adding the feature!

**Comment by HexCodeFFF** [comment]
Heh you have boring classes at my school that allow laptops to thank for that

Also the implementation could be essentially copied from esmbot, just rewritten to work with python and ffmpeg rather than C++ and ImageMagick
