### ISSUE TITLE
400, message='Bad Request', url=URL('https://api.tenor.com/v1/gifs?ids=https://gfycat.com/requiredclearcuscus&key=ECYW4F9SR5I6')

### ISSUE THREAD

**Issue by Rod-T** [HexCodeFFF/mediaforge#59]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Traceback**
If the bot uploaded a txt file with the error, please upload it here.

**Additional context**

**Comment by HexCodeFFF** [comment]
Related to #55

**Comment by HexCodeFFF** [comment]
non-tenor gifs will be silently ignored and skipped for now. i'll close #55 when i add support for other gifv platforms
