### ISSUE TITLE
Unable to run `main.py`

### ISSUE THREAD

**Issue by TheAwesomeCoder05** [HexCodeFFF/mediaforge#60]
**Describe the bug**
The bug takes place when I attempt to start the bot.

**To Reproduce**
1. Run the command `python main.py`
2. See error

**Expected behavior**
This is supposed to import the libraries and start the bot, but instead gives me this error. 

**Screenshots**
![image](https://user-images.githubusercontent.com/74418041/153121571-f91b9a0f-6783-40e9-aae3-519f9dc32465.png)

**Traceback**
None.

**Additional context**
None.

**Comment by HexCodeFFF** [comment]
You have to do "poetry install" and then "poetry run main.py"

**Comment by HexCodeFFF** [comment]
Well before thst you have to install poetry with pip

All this is documented in the README

**Comment by TheAwesomeCoder05** [comment]
Let me retry with that. Sorry I just don't do python, I'm more of a JavaScript guy haha.

**Comment by HexCodeFFF** [comment]
All good. Make to read all of the "self-hosting" header in the readme as there are additional steps beyond installing dependencies if you want full functionality
