### ISSUE TITLE
Server disconnected

### ISSUE THREAD

**Issue by LovelyProductions** [HexCodeFFF/mediaforge#63]
eemark aiohttp.client_exceptions.ServerDisconnectedError: Command raised an exception: ServerDisconnectedError: Server disconnected

[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/8053788/traceback.txt)

**Comment by HexCodeFFF** [comment]
Hosting issue

Issue with the shitty pc running mediaforhe not the code itself
