### ISSUE TITLE
Server disconnected

### ISSUE THREAD

**Issue by WWWUOP** [HexCodeFFF/mediaforge#65]
https://user-images.githubusercontent.com/99846620/154388672-96cd8280-8f69-4efa-8166-ded5a41adc40.mp4

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Traceback**
If the bot uploaded a txt file with the error, please upload it here.

**Additional context**

**Comment by HexCodeFFF** [comment]
hosting issue, cant be fixexd with better code and i dont have moners for better server
