### ISSUE TITLE
Issue with Poetry

### ISSUE THREAD

**Issue by AZMindroma** [HexCodeFFF/mediaforge#67]
**Describe the bug**
Poetry attempts to install a win32 wheel on an x64 device which results in the installation process of poetry's specified dependencies to fail.

**To Reproduce**
1. Type `python -m pip install poetry` to install poetry
2. Go to the mediaforge-master directory where the poetry.lock file is
3. Enter `poetry install` to install the various dependencies specified inside of poetry.lock
4. The first few dependencies install as normal
5. When installing cffi, error occurs as it attempts to install the win32 wheel while pip's supported wheels on this PC are arm64.

**Expected behavior**
Cffi installs as intended and goes on with the other dependencies.

**Screenshots**
![Screenshot 2022-02-19 212016](https://user-images.githubusercontent.com/69211110/154821133-d4e2d2d4-c3dc-42e1-a432-a6024d6242c3.png)

**Traceback**
None.

**Additional context**
While I tried to avoid cffi installation by modifying the poetry.lock file, running install poetry showed an error once again. I have also tried changing the wheel file inside of the artifacts folder which poetry generates which however made pip generate a new file with win32. I have tried the same process with Python 3.8 and 3.9.

**Comment by HexCodeFFF** [comment]
Hmm
Win32 *might* just be a python term for windows
I know it’s like that with sys.platform
I can’t seem to find anything on google about this which is definitely strange.
Try to run “poetry update” to regenerate the lock file from the dependencies, maybe your system doesn’t like my lock file

**Comment by HexCodeFFF** [comment]
Ok yeah I forgot that with wheels, windows x64 is “amd64” so you’re right about that

weird because cffi has amd64 packages and I believe both the development machines and hosting are all x64 so I have no idea how this happened

I’d raise a bug on poetry’s GitHub

**Comment by AZMindroma** [comment]
Yeah, there's both wheels for win32 and win_arm64. In the .lock file you made it also shows support for the arm64 wheel so it definitely seems to be an issue on Poetry's side. I'll then contact the developers of Poetry to see if they have a fix. Thank you a lot for your time! I appreciate it. :)
