### ISSUE TITLE
expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by EMHMED123** [HexCodeFFF/mediaforge#73]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Traceback**
If the bot uploaded a txt file with the error, please upload it here.

**Additional context**

**Comment by EMHMED123** [comment]
[Uploading traceback-1.txt…]()

**Comment by EMHMED123** [comment]
100

**Comment by EMHMED123** [comment]
100

**Comment by HexCodeFFF** [comment]
??

**Comment by HexCodeFFF** [comment]
Moved to #74 for some reason
