### ISSUE TITLE
$autotune on video errors out

### ISSUE THREAD

**Issue by Liberation546** [HexCodeFFF/mediaforge#75]
**Describe the bug**
When you attempt to run $autotune on a video, the bot errors and cannot autotune the video.

**To Reproduce**
1. Upload video
2. Send $autotune
3. Wait
4. Observe the error

**Expected behavior**
The audio of the attached video would be autotuned.

**Screenshots**
n/a

**Traceback**
[traceback.txt (pastebin)](https://pastebin.com/7z59GADM)

**Additional context**
n/a

**Comment by HexCodeFFF** [comment]
Ah this is a dumb bug which should have a quick fix. I'll get to it tomorrow, I'm super busy.
