### ISSUE TITLE
what the hell is going on

### ISSUE THREAD

**Issue by Fhoul** [HexCodeFFF/mediaforge#78]
DATETIME:2022-03-16 17:08:15.071788
COMMAND:$caption vehicular manslaughter
TRACEBACK:
Traceback (most recent call last):
  File "/home/hex/.cache/pypoetry/virtualenvs/mediaforge-4kydknjC-py3.8/lib/python3.8/site-packages/nextcord/ext/commands/core.py", line 168, in wrapped
    ret = await coro(*args, **kwargs) 
    
    
    caption refuses to work.

**Comment by HexCodeFFF** [comment]
Can you upload the _full_ traceback.txt file?

**Comment by Fhoul** [comment]
aiohttp.client_exceptions.ClientOSError: Command raised an exception: ClientOSError: [Errno 32] Broken pipe
DATETIME:2022-03-16 17:08:15.071788
COMMAND:$caption vehicular manslaughter
TRACEBACK:
Traceback (most recent call last):
  File "/home/hex/.cache/pypoetry/virtualenvs/mediaforge-4kydknjC-py3.8/lib/python3.8/site-packages/nextcord/ext/commands/core.py", line 168, in wrapped
    ret = await coro(*args, **kwargs) is all it said

**Comment by HexCodeFFF** [comment]
Ah
This is just a standard hosting issue on my end cause MediaForge often gets overloaded.I really should add some more user-friendly errors but other than that or buying a better PC there isn’t much I can do

**Comment by Fhoul** [comment]
thats alright, other than it being a tad slow i love your bot!

**Comment by HexCodeFFF** [comment]
Retry the command in a bit and it should work. You can also use $stats to get a decent idea of how overloaded the bot is
