### ISSUE TITLE
Unban request for 

### ISSUE THREAD

**Issue by CocaColaWithFizz** [HexCodeFFF/mediaforge#81]
** FantasticTrolling#6738**
- Your discord username including your discriminator (i.e. @Clyde#0001)
- 773960373698035722 (you can get this by enabling developer mode, right-clicking on yourself, and clicking "copy ID". this is NOT your 4 digit discriminator and will likely be 18-22 digits long.)

**Why were you banned?**
text here I got banned for spamming caption

**Why should you be unbanned?**
text here I wanna make more funny meme with bot

**Comment by HexCodeFFF** [comment]
![image](https://user-images.githubusercontent.com/35177464/160207450-fc474c32-aa23-46f8-b445-2cc8c02410a2.png)
no you were actually banned for this

**Comment by CocaColaWithFizz** [comment]
> 

yeah i did but i spammed it too hard

**Comment by HexCodeFFF** [comment]
no i manually banned you for that command, spam is unrelated to your ban

**Comment by CocaColaWithFizz** [comment]
uhhhhhhhhhhhhh

**Comment by HexCodeFFF** [comment]
💀

**Comment by CocaColaWithFizz** [comment]
so uh

**Comment by CocaColaWithFizz** [comment]
can i be unbanned pls 🥺

**Comment by HexCodeFFF** [comment]
why should i unban you
