### ISSUE TITLE
Bot goes offline when whisper command is run

### ISSUE THREAD

**Issue by micgar19** [HexCodeFFF/mediaforge#97]
### Describe the bug

I'm hosting mediaforge using docker on a digitalocean droplet, and after one of my friends tried to do the whisper command it took the bot offline.

### Traceback

no traceback

### Expected Behavior

It's expected for the bot to download the image, attach a whisper caption and then upload the image.

### Steps To Reproduce

1. Host the bot using docker
2. Send any form of media
3. Use the whisper command and type something
4. Wait, watch the bot's console for the error

### Anything Else

https://wtfwtfwtfwtf.wtf/p/2XBIXvbZo2Dn - Here's a log of the main error
https://wtfwtfwtfwtf.wtf/p/pOJt0vyvi67k - It then prints this after a couple of seconds

**Comment by HexCodeFFF** [comment]
I've experienced this specific issue when the system doesn't have enough resources. Try editing the config and lowering the number of `chrome_driver_instances` (on [line 16](https://github.com/HexCodeFFF/mediaforge/blob/feaf60233c82a87cf55a3f351323baabb0236d3f/config.example.py#L16) by default). I doubt a free hosting service can run 20 anyways.

**Comment by micgar19** [comment]
worked, thank you 👍
